import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const el=id=>document.getElementById(id),host=el('canvasHost'),status=el('status');
let catalog,rules,scene,camera,renderer,controls,content,loadedTemplate,currentMeta;
function log(s){status.textContent=s}
async function init(){
  catalog=await fetch('./config/model-catalog.json').then(r=>r.json());
  rules=await fetch('./config/electrical-rules.json').then(r=>r.json());
  for(const m of catalog.models){const o=document.createElement('option');o.value=m.id;o.textContent=m.label;el('modelSelect').appendChild(o)}
  scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc4d3);
  camera=new THREE.PerspectiveCamera(45,1,.1,5000);
  renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;host.appendChild(renderer.domElement);
  controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,20,0);
  scene.add(new THREE.HemisphereLight(0xffffff,0x334455,2.2));
  const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(80,120,70);sun.castShadow=true;scene.add(sun);
  const ground=new THREE.Mesh(new THREE.PlaneGeometry(2000,2000),new THREE.MeshStandardMaterial({color:0x567b51,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);scene.add(new THREE.GridHelper(1000,100,0x24455a,0x6f8b96));
  content=new THREE.Group();scene.add(content);resize();addEventListener('resize',resize);renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});
  el('modelSelect').onchange=loadSelected;el('autoSelectBtn').onclick=autoSelect;el('singleBtn').onclick=single;el('spanBtn').onclick=span;el('resetBtn').onclick=frame;
  await loadSelected();await span();
}
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function meta(){return catalog.models.find(x=>x.id===el('modelSelect').value)}
function autoSelect(){const circuits=Number(el('circuitsSelect').value),voltage=Number(el('voltageSelect').value),reported=Number(el('osmHeightInput').value)||null;const candidates=catalog.models.filter(m=>m.kind==='tower');let best=null;for(const m of candidates){let score=Math.abs((m.circuits||1)-circuits)*100;if(voltage<m.selection.voltageMin||voltage>m.selection.voltageMax)score+=50;if(reported)score+=Math.abs(m.nativeHeightM-reported);if(!best||score<best.score)best={m,score}}if(best){el('modelSelect').value=best.m.id;loadSelected().then(()=>{const estimate=reported||rules.voltageHeightEstimate[String(voltage)]||best.m.defaultTargetHeightM;el('heightInput').value=estimate;log(`Selección automática: ${best.m.label}\nAltura objetivo: ${estimate} m`)})}}
async function loadSelected(){currentMeta=meta();el('heightInput').value=currentMeta.defaultTargetHeightM;el('yawInput').value=currentMeta.attachmentProfile?.modelYawDeg||0;loadedTemplate=await new Promise((res,rej)=>new GLTFLoader().load(currentMeta.file,g=>res(g.scene),undefined,rej));loadedTemplate.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});log(`Modelo cargado: ${currentMeta.label}\nAltura nativa: ${currentMeta.nativeHeightM.toFixed(2)} m\nCrucetas calibradas: ${currentMeta.attachmentProfile?'sí':'no'}`)}
function clear(){while(content.children.length)content.remove(content.children[0])}
function prepared(){const obj=loadedTemplate.clone(true),target=Number(el('heightInput').value),factor=target/currentMeta.nativeHeightM;obj.scale.setScalar(factor);obj.rotation.y=THREE.MathUtils.degToRad(Number(el('yawInput').value)||0);obj.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(obj);obj.position.y-=b.min.y;obj.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(obj);const size=b.getSize(new THREE.Vector3());return{obj,height:size.y,width:size.x,depth:size.z,factor}}
function insulator(spec){const g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:0x9ed6c5,roughness:.25,metalness:.05,transparent:true,opacity:.92});for(let i=0;i<spec.discs;i++){const d=new THREE.Mesh(new THREE.CylinderGeometry(spec.discRadiusM,spec.discRadiusM,spec.lengthM/spec.discs*.42,14),mat);d.position.y=-i*spec.lengthM/spec.discs;g.add(d)}return g}
function supportPoints(height,width,meta){const p=meta.attachmentProfile||{};const levels=p.levels||[.87,.80,.74],factors=p.lateralFactors||levels.map(()=>.47),out=[];if(meta.attachmentLayout==='double-three-level'){levels.forEach((r,i)=>{out.push({x:-width*factors[i],y:height*r,z:0,id:`L${i+1}`});out.push({x:width*factors[i],y:height*r,z:0,id:`R${i+1}`})})}else{const sides=p.sides||['left','right','left'];levels.forEach((r,i)=>out.push({x:(sides[i]==='right'?1:-1)*width*factors[i],y:height*r,z:0,id:['A','B','C'][i]}));if(meta.shieldWires){const sh=p.shield||{heightRatio:.955,lateralFactor:0};out.push({x:width*(sh.lateralFactor||0),y:height*sh.heightRatio,z:0,id:'CG',shield:true})}}return out}
function addTower(z){const p=prepared();p.obj.position.z=z;content.add(p.obj);return p}
function marker(pos,color){if(!el('anchorCheck').checked)return;const m=new THREE.Mesh(new THREE.SphereGeometry(.22,12,8),new THREE.MeshBasicMaterial({color}));m.position.copy(pos);content.add(m)}
function addAccessories(towerZ,p){const voltage=String(el('voltageSelect').value),spec=rules.insulators[voltage]||rules.insulators['220000'],use=el('insulatorCheck').checked;const supports=supportPoints(p.height,p.width,currentMeta);const endpoints=[];for(const q of supports){const top=new THREE.Vector3(q.x,q.y,towerZ);marker(top,0xff3030);if(q.shield){endpoints.push({...q,z:towerZ,topY:q.y});continue}const bottomY=q.y-(use?spec.lengthM:0);if(use){const i=insulator(spec);i.position.copy(top);content.add(i)}const bottom=new THREE.Vector3(q.x,bottomY,towerZ);marker(bottom,0xffe000);endpoints.push({...q,y:bottomY,z:towerZ,topY:q.y})}return endpoints}
function cable(a,b,sag,radius,shield=false){const pts=[];for(let i=0;i<=96;i++){const t=i/96;pts.push(new THREE.Vector3(THREE.MathUtils.lerp(a.x,b.x,t),THREE.MathUtils.lerp(a.y,b.y,t)-4*sag*t*(1-t),THREE.MathUtils.lerp(a.z,b.z,t)))}const curve=new THREE.CatmullRomCurve3(pts),geo=new THREE.TubeGeometry(curve,96,radius,6,false),mat=new THREE.MeshStandardMaterial({color:shield?0xaab3ba:0x30363a,metalness:.75,roughness:.3});content.add(new THREE.Mesh(geo,mat))}
async function single(){if(!loadedTemplate)await loadSelected();clear();const p=addTower(0),a=addAccessories(0,p);frame();log(`Vista individual\nAltura real renderizada: ${p.height.toFixed(2)} m\nAnclajes: ${a.length}\nRojo = cruceta/soporte superior\nAmarillo = conexión del conductor`) }
async function span(){if(!loadedTemplate)await loadSelected();clear();if(currentMeta.kind!=='tower'){await single();log('El aerogenerador se muestra individualmente.');return}const vano=Number(el('spanInput').value),requested=Number(el('sagInput').value),left=addTower(-vano/2),right=addTower(vano/2),a=addAccessories(-vano/2,left),b=addAccessories(vano/2,right);const lowest=Math.min(...a.map(x=>x.y));const safeSag=Math.min(requested,Math.max(.5,lowest-1));if(el('wireCheck').checked){for(let i=0;i<Math.min(a.length,b.length);i++)cable(a[i],b[i],a[i].shield?safeSag*.7:safeSag,a[i].shield?rules.conductorDefaults.shieldRadiusM:rules.conductorDefaults.radiusM,a[i].shield)}frame();const adjusted=safeSag<requested?`\nAVISO: flecha limitada de ${requested.toFixed(1)} a ${safeSag.toFixed(1)} m.`:'';log(`Simulación corregida\nEje longitudinal de línea: Z\nEje transversal de crucetas: X\nVano: ${vano.toFixed(1)} m\nFlecha: ${safeSag.toFixed(1)} m\nConductores: ${a.filter(x=>!x.shield).length}\nGuardias: ${a.filter(x=>x.shield).length}${adjusted}`)}
function frame(){const b=new THREE.Box3().setFromObject(content);if(b.isEmpty()){camera.position.set(80,60,100);return}const s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3()),max=Math.max(s.x,s.y,s.z);controls.target.copy(c);camera.position.set(c.x+max*.65,c.y+max*.45,c.z+max*.75);camera.near=Math.max(.1,max/1000);camera.far=max*20;camera.updateProjectionMatrix();controls.update()}
init().catch(e=>{console.error(e);log('ERROR: '+e.message)});
