import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {ARButton} from 'three/addons/webxr/ARButton.js';
const host=document.getElementById('host'),sel=document.getElementById('model'),mode=document.getElementById('scaleMode');
const selected=JSON.parse(sessionStorage.getItem('lecaSelected')||'null');const catalog=await fetch('./config/model-catalog.json').then(r=>r.json());const rules=await fetch('./config/electrical-rules.json').then(r=>r.json());
const props=selected?.feature?.properties||{},type=selected?.type||'Sin selección';document.getElementById('selection').innerHTML=`<b>${type}</b><br>${props.NOMBRE||props.name||'Sin nombre'}<br>Voltaje: ${props.TENSION_KV||props.voltage||'s/i'}`;
for(const m of catalog.models){if(m.kind==='tower'||type.includes('eólica')){const o=document.createElement('option');o.value=m.id;o.textContent=m.label;sel.appendChild(o)}}
function recommended(){if(type.includes('eólica'))return'wind_turbine';const v=Number(props.TENSION_KV||String(props.voltage||'').split(';')[0]||220000),c=Number(props.CIRCUITO||props.circuits||1);let best,score=1e9;for(const m of catalog.models.filter(x=>x.kind==='tower')){let s=Math.abs((m.circuits||1)-c)*100;if(v<m.selection.voltageMin||v>m.selection.voltageMax)s+=50;if(s<score){score=s;best=m}}return best.id}sel.value=recommended();
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc4d3);const camera=new THREE.PerspectiveCamera(45,1,.01,5000);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.xr.enabled=true;host.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x334455,2.5));const dl=new THREE.DirectionalLight(0xffffff,2);dl.position.set(20,30,15);scene.add(dl);let content=new THREE.Group();scene.add(content);const loader=new GLTFLoader();
function resize(){renderer.setSize(host.clientWidth,host.clientHeight,false);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function lineCoords(){const g=selected?.feature?.geometry;if(!g)return[];if(g.type==='LineString')return g.coordinates;if(g.type==='MultiLineString')return g.coordinates.reduce((a,b)=>a.concat(b),[]);return[]}
function project(coords){if(!coords.length)return[];const lat0=coords.reduce((s,c)=>s+c[1],0)/coords.length,lon0=coords.reduce((s,c)=>s+c[0],0)/coords.length,R=6371000,cos=Math.cos(lat0*Math.PI/180);return coords.map(c=>new THREE.Vector3((c[0]-lon0)*Math.PI/180*R*cos,0,-(c[1]-lat0)*Math.PI/180*R))}
function cumulative(p){const d=[0];for(let i=1;i<p.length;i++)d.push(d.at(-1)+p[i].distanceTo(p[i-1]));return d}
function atDistance(p,d,cs){if(d<=0)return p[0].clone();if(d>=cs.at(-1))return p.at(-1).clone();let i=1;while(cs[i]<d)i++;return p[i-1].clone().lerp(p[i],(d-cs[i-1])/(cs[i]-cs[i-1]))}
function tangentAt(p,d,cs){const eps=Math.max(1,cs.at(-1)/10000);return atDistance(p,Math.min(cs.at(-1),d+eps),cs).sub(atDistance(p,Math.max(0,d-eps),cs)).normalize()}
function curve(a,b,sag){const pts=[];for(let i=0;i<=32;i++){const t=i/32;pts.push(new THREE.Vector3().lerpVectors(a,b,t).add(new THREE.Vector3(0,-4*sag*t*(1-t),0)))}return new THREE.CatmullRomCurve3(pts)}
function insulator(spec){const g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:0x9ed6c5});for(let i=0;i<spec.discs;i++){const x=new THREE.Mesh(new THREE.CylinderGeometry(spec.discRadiusM,spec.discRadiusM,spec.lengthM/spec.discs*.42,10),mat);x.position.y=-i*spec.lengthM/spec.discs;g.add(x)}return g}
async function load(meta){return new Promise((r,j)=>loader.load(meta.file,g=>r(g.scene),undefined,j))}
async function build(){scene.remove(content);content=new THREE.Group();scene.add(content);const meta=catalog.models.find(m=>m.id===sel.value),base=await load(meta);if(meta.kind==='wind'){base.scale.setScalar(8/meta.nativeHeightM);content.add(base);return}let path=project(lineCoords());if(path.length<2){path=[new THREE.Vector3(0,0,-10),new THREE.Vector3(0,0,10)]}const cs=cumulative(path),length=cs.at(-1),spacing=Math.max(80,Math.min(350,length/Math.max(2,Math.ceil(length/250)))),count=Math.min(60,Math.max(2,Math.ceil(length/spacing)+1));const ds=Array.from({length:count},(_,i)=>length*i/(count-1));const fit=mode.value==='fit'?20/Math.max(length,1):1;path=path.map(x=>x.multiplyScalar(fit));const targetH=(meta.defaultTargetHeightM||meta.nativeHeightM)*fit,modelScale=targetH/meta.nativeHeightM,spec=rules.insulators[String(Number(props.TENSION_KV||220000))]||rules.insulators['220000'];const towers=[];
 for(const d0 of ds){const d=d0*fit,p=atDistance(path,d,cumulative(path)),t=tangentAt(path,d,cumulative(path));const tower=base.clone(true);tower.scale.setScalar(modelScale);tower.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(tower),center=box.getCenter(new THREE.Vector3());tower.position.set(p.x-center.x,-box.min.y,p.z-center.z);tower.rotation.y=Math.atan2(t.x,t.z);content.add(tower);tower.updateMatrixWorld(true);const attachments=[];for(const a of meta.attachmentProfile.attachmentsNative){const top=new THREE.Vector3(a.x*modelScale,a.y*modelScale,a.z*modelScale).applyAxisAngle(new THREE.Vector3(0,1,0),tower.rotation.y).add(p);if(!a.shield){const ins=insulator({...spec,lengthM:spec.lengthM*fit,discRadiusM:spec.discRadiusM*fit});ins.position.copy(top);content.add(ins);top.y-=spec.lengthM*fit}attachments.push({id:a.id,p:top,shield:a.shield})}towers.push(attachments)}
 for(let i=0;i<towers.length-1;i++){for(const a of towers[i]){const b=towers[i+1].find(x=>x.id===a.id);if(!b)continue;const span=a.p.distanceTo(b.p),sag=Math.min(span*.06,12*fit),rad=(a.shield?rules.conductorDefaults.shieldRadiusM:rules.conductorDefaults.radiusM)*Math.max(fit,.2);const geo=new THREE.TubeGeometry(curve(a.p,b.p,sag),32,rad,5,false);content.add(new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:a.shield?0xaab3ba:0x333333,metalness:.7}))}}}
 const box=new THREE.Box3().setFromObject(content),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),mx=Math.max(size.x,size.y,size.z);controls.target.copy(center);camera.position.set(center.x+mx*.65,center.y+mx*.45,center.z+mx*.75);camera.near=.01;camera.far=Math.max(1000,mx*30);camera.updateProjectionMatrix();controls.update();document.getElementById('selection').innerHTML+=`<br><b>Longitud reconstruida:</b> ${(length/1000).toFixed(2)} km · ${count} torres`}
await build();sel.onchange=build;mode.onchange=build;document.getElementById('preview').onclick=build;const arButton=ARButton.createButton(renderer,{requiredFeatures:['hit-test'],optionalFeatures:['dom-overlay'],domOverlay:{root:document.body}});arButton.style.display='none';document.body.appendChild(arButton);document.getElementById('enterAR').onclick=()=>{if(!navigator.xr){alert('WebXR AR no está disponible. En iPad será necesario USDZ/Quick Look o una aplicación ARKit. La vista 3D completa sí funciona.');return}if(mode.value==='real'&&!confirm('La línea a escala real puede quedar fuera del campo visible. ¿Continuar?'))return;arButton.click()};renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});
