import * as THREE from 'three';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {ARButton} from 'three/addons/webxr/ARButton.js';
const host=document.getElementById('host'),sel=document.getElementById('model');const selected=JSON.parse(sessionStorage.getItem('lecaSelected')||'null');const catalog=await fetch('./config/model-catalog.json').then(r=>r.json());const rules=await fetch('./config/electrical-rules.json').then(r=>r.json());
const props=selected?.feature?.properties||{};const type=selected?.type||'Sin selección';document.getElementById('selection').innerHTML=`<b>${type}</b><br>${props.NOMBRE||props.name||'Sin nombre'}<br>Voltaje: ${props.TENSION_KV||props.voltage||'s/i'}`;
for(const m of catalog.models){const o=document.createElement('option');o.value=m.id;o.textContent=m.label;sel.appendChild(o)}
function recommended(){if(type.includes('eólica'))return'wind_turbine';const v=Number(props.TENSION_KV||String(props.voltage||'').split(';')[0]||220000);const circuits=Number(props.CIRCUITO||props.circuits||1);const towers=catalog.models.filter(m=>m.kind==='tower');let best=towers[0],score=1e9;for(const m of towers){let s=Math.abs((m.circuits||1)-circuits)*100;if(v<m.selection.voltageMin||v>m.selection.voltageMax)s+=50;if(s<score){score=s;best=m}}return best.id}sel.value=recommended();
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc4d3);const camera=new THREE.PerspectiveCamera(45,1,.01,1000);camera.position.set(14,10,18);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.xr.enabled=true;host.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,5,0);scene.add(new THREE.HemisphereLight(0xffffff,0x334455,2.5));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(20,30,15);scene.add(light);let content=new THREE.Group();scene.add(content);const loader=new GLTFLoader();
function resize(){renderer.setSize(host.clientWidth,host.clientHeight,false);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function clear(){scene.remove(content);content=new THREE.Group();scene.add(content)}
function load(meta){return new Promise((res,rej)=>loader.load(meta.file,g=>res(g.scene),undefined,rej))}
function curve(a,b,sag=.8){const pts=[];for(let i=0;i<=48;i++){const t=i/48;pts.push(new THREE.Vector3(THREE.MathUtils.lerp(a.x,b.x,t),THREE.MathUtils.lerp(a.y,b.y,t)-4*sag*t*(1-t),THREE.MathUtils.lerp(a.z,b.z,t)))}return new THREE.CatmullRomCurve3(pts)}
async function build(){clear();const meta=catalog.models.find(m=>m.id===sel.value),base=await load(meta);if(meta.kind==='wind'){const scale=8/meta.nativeHeightM;base.scale.setScalar(scale);base.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(base);base.position.y-=b.min.y;content.add(base);return}const scale=8/meta.nativeHeightM;const towerA=base.clone(true),towerB=base.clone(true);towerA.scale.setScalar(scale);towerB.scale.setScalar(scale);towerA.position.z=-5;towerB.position.z=5;for(const t of[towerA,towerB]){t.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(t);t.position.y-=b.min.y}content.add(towerA,towerB);const h=8,w=meta.nativeWidthM*scale,p=meta.attachmentProfile||{},levels=p.levels||[.87,.8,.74],facts=p.lateralFactors||[.47,.49,.47],points=[];if(meta.circuits===2){levels.forEach((r,i)=>{points.push([-w*facts[i],h*r],[w*facts[i],h*r])})}else{levels.forEach((r,i)=>points.push([(i===1?1:-1)*w*facts[i],h*r]))}for(const [x,y]of points){const a=new THREE.Vector3(x,y,-5),b=new THREE.Vector3(x,y,5),geo=new THREE.TubeGeometry(curve(a,b,.7),48,.018,6,false);content.add(new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:0x333333,metalness:.7})))}}
await build();sel.onchange=build;document.getElementById('preview').onclick=build;const arButton=ARButton.createButton(renderer,{requiredFeatures:['hit-test'],optionalFeatures:['dom-overlay'],domOverlay:{root:document.body}});arButton.style.display='none';document.body.appendChild(arButton);document.getElementById('enterAR').onclick=()=>{if(!navigator.xr){alert('Este navegador no ofrece WebXR AR. En Android use Chrome compatible. En iPad se requerirá USDZ/Quick Look para AR nativa.');return}arButton.click()};renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});
